package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.FoodGroupDto;
import com.gg.gpos.menu.entity.FoodGroup;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface FoodGroupMapper {
	FoodGroup dtoToEntity(FoodGroupDto foodGroupDto);
	
	@Mapping(target = "foodGroupItems", expression ="java(null)")
	FoodGroupDto entityToDto(FoodGroup foodGroup);
}