package com.gg.gpos.menu.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import com.gg.gpos.common.constant.FoodTypeEnum;
import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "food_item")
@EntityListeners(AuditEntityListener.class)
public class FoodItem {
	  @Id
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"item_id\"", nullable = true)
	  private Long itemId;
	  @Column(name = "\"parent_id\"", nullable = true)
	  private Long parentId;
	  @Column(name = "\"type\"", nullable = true)
	  private String type;
	  @Column(name = "\"code\"", nullable = true)
	  private String code;
	  @Column(name = "\"name\"", nullable = true)
	  private String name;
	  @Column(name = "\"unsigned_name\"", nullable = true)
	  private String unsignedName;
	  @Column(name = "\"status\"", nullable = true)
	  private Integer status;
	  @Column(name = "\"modi_scheme\"", nullable = true)
	  private Integer modiScheme;
	  @Column(name = "\"combo_scheme\"", nullable = true)
	  private Integer comboScheme;
	  @Column(name = "\"combo_join_mode\"", nullable = true)
	  private Integer comboJoinMode;
	  @Column(name = "\"right_lvl\"", nullable = true)
	  private String rightLvl;
	  @Column(name = "\"object_sifr\"", nullable = true)
	  private Integer objectSifr;
	  @Column(name = "\"flags\"", nullable = true)
	  private Integer flags;	
	  @Column(name = "\"sap_code\"", nullable = true)
	  private String sapCode;
	  @Column(name = "\"cook_mins\"", nullable = true)
	  private Integer cookMins;	
  
	  //@ManyToOne(fetch = FetchType.LAZY)
	  //@JoinColumn(name = "parent_id", nullable = true)
	  //private FoodItem parent;
	  
	  @OneToMany(mappedBy = "foodItem",fetch = FetchType.LAZY)
	  private List<FoodGroupItem> foodGroupItems;
	  
	  @PrePersist
	  private void beforePersist() {
		  setType(FoodTypeEnum.MENU_ITEM.val);
	  }
	  
	  @PreUpdate
	  private void beforeUpdate() {
		  setType(FoodTypeEnum.MENU_ITEM.val);
	  }
  
}