package com.gg.gpos.integration.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class Province {
  private Long id;
  private String name;
  private Integer order;
}