package com.gg.gpos.menu.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "modifier")
@EntityListeners(AuditEntityListener.class)
public class Modifier {
	  @Id
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"item_id\"", nullable = true)
	  private Long itemId;
	  @Column(name = "\"parent_id\"", nullable = true)
	  private Long parentId;
	  @Column(name = "\"code\"", nullable = true)
	  private String code;
	  @Column(name = "\"name\"", nullable = true)
	  private String name;
	  @Column(name = "\"unsigned_name\"", nullable = true)
	  private String unsignedName;
	  @Column(name = "\"status\"", nullable = true)
	  private Integer status;
	  @Column(name = "\"dish\"", nullable = true)
	  private Integer dish;
	  @Column(name = "\"max_one_dish\"", nullable = true)
	  private Integer maxOneDish;
	  @Column(name = "\"right_lvl\"", nullable = true)
	  private String rightLvl;
	  @Column(name = "\"object_sifr\"", nullable = true)
	  private Integer objectSifr;
	  @Column(name = "\"flags\"", nullable = true)
	  private Integer flags;
	  
	  @OneToMany(mappedBy = "modifier",fetch = FetchType.LAZY)
	  private List<CoFoodItemModifier> coFoodItemModifiers;
}