package com.gg.gpos.reference.dto;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class SystemParameterDto extends BaseDto{
  private Long id;
  private String paramName;
  private String paramValue;
  private String description;
  private Integer version;
}