package com.gg.gpos.menu.dto;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class KdsDto extends BaseDto {
  private Long id;
  private String name;
  private boolean status;
  private String createdBy;
  private LocalDateTime createdDate;
  private String modifiedBy;
  private LocalDateTime modifiedDate;
  private Integer restaurantCode;
  
  private List<KitchenDto> kitchens;
  private List<PrintGroupDto> printGroups;
  private String selectedRestaurantCodes;
  private List<Integer> resCodes;
  private boolean override;
  
  public String getDisplayCreatedDate() {
	  if (createdDate != null) {
		  return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
	  } else {
		  return null;
	  }
  }
}