package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "currency")
@EntityListeners(AuditEntityListener.class)
public class Currency {
	  @Id
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"item_ident\"", nullable = true)
	  private Long itemIdent;
	  @Column(name = "\"status\"", nullable = true)
	  private String status;
	  @Column(name = "\"rate_class\"", nullable = true)
	  private String rateClass;
	  @Column(name = "\"code\"", nullable = true)
	  private String code;
}