package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "feature")
@EntityListeners(AuditEntityListener.class)
public class Feature {
	  @Id
	  @Column(name = "\"id\"")
	  @GeneratedValue(strategy=GenerationType.IDENTITY)
	  private Long id;
	  @Column(name = "\"parent_id\"", nullable = true)
	  private Long parentId;
	  @Column(name = "\"restaurant_code\"", nullable = true)
	  private Integer restaurantCode;
	  @Column(name = "\"code\"", nullable = true)
	  private String code;
	  @Column(name = "\"name_en\"", nullable = true)
	  private String nameEn;
	  @Column(name = "\"name_vn\"", nullable = true)
	  private String nameVn;
	  @Column(name = "\"status\"", nullable = true)
	  private Integer status;
	  @Column(name = "\"desc_en\"", nullable = true)
	  private String descEn;
	  @Column(name = "\"desc_vn\"", nullable = true)
	  private String descVn;
	  
//	  @ManyToMany()
//	  @JoinTable(name="co_food_item_feature", joinColumns = {
//	      @JoinColumn(name="feature_id", nullable=false, updatable=false) }, 
//	  	inverseJoinColumns = { @JoinColumn(name="co_food_item_id", nullable=false, updatable=false) })
//	  public List<CoFoodItem> coFoodItems;
}

