package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"foodGroup", "foodItem"})
@Entity
@Table(name = "food_group_item")
@EntityListeners(AuditEntityListener.class)
public class FoodGroupItem {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"restaurant_code\"", nullable = true)
  private Integer restaurantCode;
  @Column(name = "\"item_order\"", nullable = true)
  private Integer itemOrder;
  @Column(name = "\"changed\"", nullable = true)
  private Integer changed;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"food_group_id\"", nullable = false)
  private FoodGroup foodGroup;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"food_item_id\"", nullable = false)
  private FoodItem foodItem;  
}