package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "modi_scheme_detail")
@EntityListeners(AuditEntityListener.class)
public class ModiSchemeDetail {
	  @Id
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"item_id\"", nullable = true)
	  private Long itemId;
	  @Column(name = "\"parent_id\"", nullable = true)
	  private Long parentId;
	  @Column(name = "\"changes_price\"", nullable = true)
	  private Integer changesPrice;
	  @Column(name = "\"use_down_limit\"", nullable = true)
	  private Integer useDownLimit;
	  @Column(name = "\"up_limit\"", nullable = true)
	  private Integer upLimit;
	  @Column(name = "\"free_count\"", nullable = true)
	  private Integer freeCount;
	  @Column(name = "\"source_ident\"", nullable = true)
	  private Integer sourceIdent;
	  @Column(name = "\"sort_num\"", nullable = true)
	  private Integer sortNum;
	  @Column(name = "\"read_only_name\"", nullable = true)
	  private String readOnlyName;
	  @Column(name = "\"use_up_limit\"", nullable = true)
	  private Integer useUpLimit;
	  @Column(name = "\"modi_group\"", nullable = true)
	  private Integer modiGroup;
	  @Column(name = "\"sh_quantity\"", nullable = true)
	  private Integer shQuantity;
	  @Column(name = "\"assign_childs_on_server\"", nullable = true)
	  private Integer assignChildsOnServer;
	  @Column(name = "\"replace_def_modifier\"", nullable = true)
	  private Integer replaceDefModifier;
	  @Column(name = "\"down_limit\"", nullable = true)
	  private Integer downLimit;
	  @Column(name = "\"default_modifier\"", nullable = true)
	  private Integer defaultModifier;
	  @Column(name = "\"modi_scheme\"", nullable = true)
	  private Integer modiScheme;
	  @Column(name = "\"object_sifr\"", nullable = true)
	  private Integer objectSifr;
	  @Column(name = "\"flags\"", nullable = true)
	  private Integer flags;
}