package com.gg.gpos.menu.entity;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"groupParam"})
@Entity
@Table(name = "param")
@EntityListeners(AuditEntityListener.class)
public class Param {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"restaurant_code\"", nullable = true)
  private Integer restaurantCode;
  @Column(name = "\"type\"", nullable = true)
  private String type;
  @Column(name = "\"param_code\"", nullable = false)
  private String paramCode;
  @Column(name = "\"param_value\"", nullable = true)
  private String paramValue;
  @Column(name = "\"description\"", nullable = true)
  private String description;
  @Column(name = "\"status\"", nullable = true)
  private boolean status;
  @Column(name = "\"created_by\"", nullable = true)
  private String createdBy;
  @Column(name = "\"created_date\"", nullable = true)
  private LocalDateTime createdDate;
  @Column(name = "\"modified_by\"", nullable = true)
  private String modifiedBy;
  @Column(name = "\"modified_date\"", nullable = true)
  private LocalDateTime modifiedDate;
  @Column(name = "\"name\"", nullable = true)
  private String name;
  @Column(name = "\"check_time_range\"", nullable = true)
  private boolean checkTimeRange;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"group_param_id\"", nullable = false)
  private GroupParam groupParam;


  @PrePersist
  private void beforePersist() {
	setCreatedDate(LocalDateTime.now());
	setModifiedDate(LocalDateTime.now());
  }
  
  @PreUpdate
  private void beforeUpdate() {
	  setModifiedDate(LocalDateTime.now());
  }

}