package com.gg.gpos.menu.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"kds"})
@Entity
@Table(name = "print_group")
@EntityListeners(AuditEntityListener.class)
public class PrintGroup {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"restaurant_code\"", nullable = true)
  private Integer restaurantCode;
  @Column(name = "\"code\"", nullable = true)
  private String code;
  @Column(name = "\"kitchen_type\"", nullable = true)
  private String kitchenType;
	  
  @ManyToOne()
  @JoinColumn(name = "\"kds_id\"", nullable = true)
  private Kds kds;

  @ManyToMany()
  @JoinTable(name="print_group_food_item", joinColumns = {
      @JoinColumn(name="print_group_id", nullable=false, updatable=false) }, 
  	inverseJoinColumns = { @JoinColumn(name="food_item_id", nullable=false, updatable=false) })
  	public List<FoodItem> foodItems;
}