package com.gg.gpos.reference.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.gg.gpos.reference.entity.Attachment;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Repository
public interface AttachmentRepository extends JpaRepository<Attachment, Long>, JpaSpecificationExecutor<Attachment> {
	List<Attachment> findByModuleIdAndModuleTypeAndFunctionType(Long moduleId, String moduleType, String functionType);
	List<Attachment> findByModuleIdAndModuleTypeAndFunctionTypeNot(Long moduleId, String moduleType, String functionType);
	List<Attachment> findByModuleIdAndModuleType(Long moduleId, String moduleType);
	List<Attachment> findByModuleTypeAndFunctionTypeIsNullAndModuleIdIsNull(String moduleType);
	List<Attachment> findBySyncStatus(String status);
	Long countByAbsolutePath(String absolutePath);
	Attachment findByModuleIdAndModuleTypeAndFunctionTypeAndAbsolutePath(Long moduleId, String moduleType, String functionType,String absolutePath);
	void deleteByModuleIdAndModuleTypeAndFunctionType(Long moduleId, String moduleType, String functionType);
	void deleteByModuleIdAndModuleType(Long moduleId, String moduleType);
}