//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.01 at 05:41:12 PM ICT 
//


package com.gg.rk7.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gg.rk7.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RK7QueryResultRK7ReferenceItemsItemChildsChild_QNAME = new QName("", "Child");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gg.rk7.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RK7QueryResult }
     * 
     */
    public RK7QueryResult createRK7QueryResult() {
        return new RK7QueryResult();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference }
     * 
     */
    public RK7QueryResult.RK7Reference createRK7QueryResultRK7Reference() {
        return new RK7QueryResult.RK7Reference();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items }
     * 
     */
    public RK7QueryResult.RK7Reference.Items createRK7QueryResultRK7ReferenceItems() {
        return new RK7QueryResult.RK7Reference.Items();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items.Item }
     * 
     */
    public RK7QueryResult.RK7Reference.Items.Item createRK7QueryResultRK7ReferenceItemsItem() {
        return new RK7QueryResult.RK7Reference.Items.Item();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items.Item.Childs }
     * 
     */
    public RK7QueryResult.RK7Reference.Items.Item.Childs createRK7QueryResultRK7ReferenceItemsItemChilds() {
        return new RK7QueryResult.RK7Reference.Items.Item.Childs();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items.Item.LimitDishes }
     * 
     */
    public RK7QueryResult.RK7Reference.Items.Item.LimitDishes createRK7QueryResultRK7ReferenceItemsItemLimitDishes() {
        return new RK7QueryResult.RK7Reference.Items.Item.LimitDishes();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult }
     * 
     */
    public RK7QueryResult.CommandResult createRK7QueryResultCommandResult() {
        return new RK7QueryResult.CommandResult();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference createRK7QueryResultCommandResultRK7Reference() {
        return new RK7QueryResult.CommandResult.RK7Reference();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference.Items }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference.Items createRK7QueryResultCommandResultRK7ReferenceItems() {
        return new RK7QueryResult.CommandResult.RK7Reference.Items();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference.Items.Item }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference.Items.Item createRK7QueryResultCommandResultRK7ReferenceItemsItem() {
        return new RK7QueryResult.CommandResult.RK7Reference.Items.Item();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs createRK7QueryResultCommandResultRK7ReferenceItemsItemChilds() {
        return new RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items.Item.Childs.Child }
     * 
     */
    public RK7QueryResult.RK7Reference.Items.Item.Childs.Child createRK7QueryResultRK7ReferenceItemsItemChildsChild() {
        return new RK7QueryResult.RK7Reference.Items.Item.Childs.Child();
    }

    /**
     * Create an instance of {@link RK7QueryResult.RK7Reference.Items.Item.LimitDishes.Data }
     * 
     */
    public RK7QueryResult.RK7Reference.Items.Item.LimitDishes.Data createRK7QueryResultRK7ReferenceItemsItemLimitDishesData() {
        return new RK7QueryResult.RK7Reference.Items.Item.LimitDishes.Data();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference.Items.Item.RecommendedMenuItems }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference.Items.Item.RecommendedMenuItems createRK7QueryResultCommandResultRK7ReferenceItemsItemRecommendedMenuItems() {
        return new RK7QueryResult.CommandResult.RK7Reference.Items.Item.RecommendedMenuItems();
    }

    /**
     * Create an instance of {@link RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs.Child }
     * 
     */
    public RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs.Child createRK7QueryResultCommandResultRK7ReferenceItemsItemChildsChild() {
        return new RK7QueryResult.CommandResult.RK7Reference.Items.Item.Childs.Child();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RK7QueryResult.RK7Reference.Items.Item.Childs.Child }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Child", scope = RK7QueryResult.RK7Reference.Items.Item.Childs.class)
    public JAXBElement<RK7QueryResult.RK7Reference.Items.Item.Childs.Child> createRK7QueryResultRK7ReferenceItemsItemChildsChild(RK7QueryResult.RK7Reference.Items.Item.Childs.Child value) {
        return new JAXBElement<RK7QueryResult.RK7Reference.Items.Item.Childs.Child>(_RK7QueryResultRK7ReferenceItemsItemChildsChild_QNAME, RK7QueryResult.RK7Reference.Items.Item.Childs.Child.class, RK7QueryResult.RK7Reference.Items.Item.Childs.class, value);
    }

}
