package com.gg.gpos.res.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class BrandDto {
  private Long id;
  private String name;
  private String longName;
  private Integer displayOrder;
}