package com.gg.gpos.res.dto;

import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class ProvinceDto {
  private Long id;
  private String name;
  private Integer displayOrder;
  
  private ZoneDto zone;
  private List<DistrictDto> districts;
  private List<ProvinceBrandDto> provinceBrands;
}