package com.gg.gpos.res.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class RestaurantUserDto {
  private Long id;
  private Integer restaurantCode;
  private String username;
  
  private RestaurantDto restaurant;

  public RestaurantUserDto() {
	super();
  }

  public RestaurantUserDto(Integer restaurantCode, String username) {
	super();
	this.restaurantCode = restaurantCode;
	this.username = username;
  }	  
}