package com.gg.gpos.res.dto;

import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class ZoneDto {
  private Long id;
  private String code;
  private String name;
  
  private List<ProvinceDto> provinces;
}