package com.gg.gpos.res.dto;

import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class DistrictBrandDto {
  private Long id;
  private DistrictDto district;
  private BrandDto brand;
  
  private List<RestaurantDto> restaurants;
}