package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.SoCategoryDto;
import com.gg.gpos.menu.dto.SoCategoryFoodGroupDto;
import com.gg.gpos.menu.dto.SoDto;
import com.gg.gpos.menu.entity.So;
import com.gg.gpos.menu.entity.SoCategory;
import com.gg.gpos.menu.entity.SoCategoryFoodGroup;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface SoCategoryMapper {
	SoCategory dtoToEntity(SoCategoryDto soCategoryDto);
	SoCategoryDto entityToDto(SoCategory soCategory);
	
	@Mapping(target = "soCategories", expression = "java(null)")
	SoDto soToSoDto(So so);
	
	@Mapping(target = "foodGroup", expression = "java(null)")
	@Mapping(target = "soCategory", expression = "java(null)")
	SoCategoryFoodGroupDto soCategoryFoodGroupToSoCategoryFoodGroupDto(SoCategoryFoodGroup soCategoryFoodGroup);
	
	/*@Mapping(target = "soCategory", expression = "java(null)")
	@Mapping(target = "coFoodGroupDisplays", expression = "java(null)")
	CoCategoryDto coCategoryToCoCategoryDto(CoCategory coCategory);	*/
}