package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.res.dto.BrandDto;
import com.gg.gpos.res.entity.Brand;


/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface BrandMapper {
	Brand dtoToEntity(BrandDto brandDto);
	BrandDto entityToDto(Brand brand);
}