package com.gg.gpos.res.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "brand")
public class Brand {

  @Id
  //@GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"name\"", nullable = false)
  private String name;
  @Column(name = "\"long_name\"", nullable = true)
  private String longName;
  @Column(name = "\"display_order\"", nullable = true)
  private Integer displayOrder;
}