package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@Entity
@Table(name = "restaurant_master")
@EntityListeners(AuditEntityListener.class)
public class RestaurantMaster {
	  @Id
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"item_id\"", nullable = true)
	  private Long itemId;
	  @Column(name = "\"parent_id\"", nullable = true)
	  private Long parentId;
	  @Column(name = "\"code\"", nullable = true)
	  private String code;
	  @Column(name = "\"name\"", nullable = true)
	  private String name;
	  @Column(name = "\"status\"", nullable = true)
	  private Integer status;
	  @Column(name = "\"object_sifr\"", nullable = true)
	  private Integer objectSifr;
	  @Column(name = "\"flags\"", nullable = true)
	  private Integer flags;
	  
	  @Column(name = "\"gen_ggg_rname\"", nullable = true)
	  private String genGggRname;
	  @Column(name = "\"gen_ggg_tel\"", nullable = true)
	  private String genGggTel;
	  @Column(name = "\"gen_ggg_add\"", nullable = true)
	  private String genGggAdd;
	  @Column(name = "\"gen_ggg_web\"", nullable = true)
	  private String genGggWeb;
	  @Column(name = "\"gen_ggg_rco\"", nullable = true)
	  private String genGggRco;
	  @Column(name = "\"gen_sap_code\"", nullable = true)
	  private String genSapCode;
	  @Column(name = "\"gen_ggg_brand\"", nullable = true)
	  private String genGggBrand;
	  @Column(name = "\"gen_sap_bank_terminal_id\"", nullable = true)
	  private String genSapBankTerminalId;
}