package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"soCategory", "foodGroup"})
@Entity
@Table(name = "so_category_food_group")
@EntityListeners(AuditEntityListener.class)
public class SoCategoryFoodGroup {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"restaurant_code\"", nullable = true)
  private Integer restaurantCode;
  @Column(name = "\"food_group_parent_id\"", nullable = true)
  private Long foodGroupParentId;
  @Column(name = "\"group_order\"", nullable = true)
  private Integer groupOrder;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"so_category_id\"", nullable = false)
  private SoCategory soCategory;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"food_group_id\"", nullable = true)
  private FoodGroup foodGroup;  
}