package com.gg.gpos.res.manager;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.gg.gpos.res.dto.ProvinceDto;
import com.gg.gpos.res.entity.Province;
import com.gg.gpos.res.mapper.ProvinceMapper;
import com.gg.gpos.res.repository.ProvinceRepository;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Service
public class ProvinceManager {
	private ProvinceRepository provinceRepository;
	@Autowired
	public void setProvinceRepository(ProvinceRepository provinceRepository) {
		this.provinceRepository = provinceRepository;
	}
	private ProvinceMapper provinceMapper;
	@Autowired
	public void setProvinceMapper(ProvinceMapper provinceMapper) {
		this.provinceMapper = provinceMapper;
	}
	
	public ProvinceDto get(Long id) {
		return provinceRepository.findById(id).map(provinceMapper::entityToDto).orElse(null);
	}
	
	public List<ProvinceDto> gets() {
		return provinceRepository.findAll().stream().map(provinceMapper::entityToDto).collect(Collectors.toList());
	}
	
	public ProvinceDto save(ProvinceDto provinceDto) {
		Province province = Optional.ofNullable(provinceDto).map(provinceMapper::dtoToEntity).orElse(null);
		if (province != null) {
			return Optional.ofNullable(provinceRepository.save(province)).map(provinceMapper::entityToDto).orElse(null);
		} else {
			return null;
		}
	}
}