package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.FoodItemDto;
import com.gg.gpos.menu.dto.KdsDto;
import com.gg.gpos.menu.dto.PrintGroupDto;
import com.gg.gpos.menu.entity.FoodItem;
import com.gg.gpos.menu.entity.Kds;
import com.gg.gpos.menu.entity.PrintGroup;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface PrintGroupMapper {
	PrintGroup dtoToEntity(PrintGroupDto printGroupDto);
	PrintGroupDto entityToDto(PrintGroup printGroup);
	
	@Mapping(target = "printGroups", expression = "java(null)")
	KdsDto kdsToKdsDto(Kds kds);
	
	@Mapping(target = "foodGroupItems", expression = "java(null)")
	FoodItemDto foodItemToFoodItemDto(FoodItem foodItem);
}