package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.FoodItemDto;
import com.gg.gpos.menu.entity.FoodItem;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface FoodItemMapper {
	FoodItem dtoToEntity(FoodItemDto foodItemDto);

	@Mapping(target = "foodGroupItems", expression ="java(null)")
	FoodItemDto entityToDto(FoodItem foodItem);
}