package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.res.dto.ProvinceDto;
import com.gg.gpos.res.entity.Province;




/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface ProvinceMapper {
	Province dtoToEntity(ProvinceDto provinceDto);
	ProvinceDto entityToDto(Province province);
}