package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.OrderCategoryDto;
import com.gg.gpos.menu.dto.SoCategoryDto;
import com.gg.gpos.menu.entity.OrderCategory;
import com.gg.gpos.menu.entity.SoCategory;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface OrderCategoryMapper {
	OrderCategory dtoToEntity(OrderCategoryDto orderCategoryDto);
	OrderCategoryDto entityToDto(OrderCategory orderCategory);
	
	/*@Mapping(target = "orderCategory", expression = "java(null)")
	@Mapping(target = "so", expression = "java(null)")
	SoCategoryDto soCategoryToSoCategoryDto(SoCategory soCategory);	*/
}