package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.GroupParamDto;
import com.gg.gpos.menu.dto.ParamDto;
import com.gg.gpos.menu.entity.GroupParam;
import com.gg.gpos.menu.entity.Param;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface ParamMapper {
	Param dtoToEntity(ParamDto paramDto);
	ParamDto entityToDto(Param param);
	
	@Mapping(target = "params", expression = "java(null)")
	GroupParamDto groupParamToGroupParamDto(GroupParam groupParam);
}