package com.gg.gpos.user.dto;

import java.util.ArrayList;
import java.util.List;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class StaffDto extends BaseDto {
  private Long id;
  private String fullname;
  private String position;
  private String email;
  private String phone;
  private boolean status;
  
  private AppUserDto user;
  private AppGroupDto group;
  List<Long> roleIds = new ArrayList<>();
}