package com.gg.gpos.res.dto;

import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class DistrictDto {
  private Long id;
  private String name;
  private Integer displayOrder;
  
  private ProvinceDto province;
  private List<DistrictBrandDto> districtBrands;
}