package com.gg.gpos.menu.controller;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.servlet.ModelAndView;

import com.gg.gpos.controller.BaseController;
import com.gg.gpos.menu.dto.SoCategoryFoodGroupDto;
import com.gg.gpos.menu.manager.SoCategoryFoodGroupManager;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class SoCategoryFoodGroupController extends BaseController {

    private SoCategoryFoodGroupManager soCategoryFoodGroupManager;

    @Autowired
    public void setSoCategoryFoodGroupManager(SoCategoryFoodGroupManager soCategoryFoodGroupManager) {
        this.soCategoryFoodGroupManager = soCategoryFoodGroupManager;
    }

    @GetMapping("/soCategoryFoodGroup/list")
    public ModelAndView list(HttpServletRequest request) throws Exception {
    	log.debug("entering 'list' method...");
    	
		ModelAndView modelAndView = new ModelAndView("soCategoryFoodGroup-list");
		modelAndView.addObject("soCategoryFoodGroups", soCategoryFoodGroupManager.gets());

        return modelAndView;
    }
    
    @ModelAttribute
    @GetMapping("/soCategoryFoodGroup/edit/{id}")
    public ModelAndView show(@PathVariable ("id") @NotNull Long id) throws Exception {
    	log.debug("entering 'show' method...");
    
    	ModelAndView modelAndView = new ModelAndView("soCategoryFoodGroup-form");
        modelAndView.addObject(soCategoryFoodGroupManager.get(id));

        return modelAndView;
    }

    @PostMapping("/soCategoryFoodGroup/save")
    public String save(@Valid SoCategoryFoodGroupDto soCategoryFoodGroupDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) throws Exception {
        log.debug("entering 'save' method...");

        Locale locale = request.getLocale();
        String view = "soCategoryFoodGroup-form";
        
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
            return view;
        }

        soCategoryFoodGroupManager.save(soCategoryFoodGroupDto);
        addMessage(request, getText("soCategoryFoodGroup.updated", locale));
        view = "redirect:/soCategoryFoodGroup/list";

        return view;
    }
    
}