package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.CategoryDto;
import com.gg.gpos.menu.entity.Category;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface CategoryMapper {
	Category dtoToEntity(CategoryDto categoryDto);
	CategoryDto entityToDto(Category category);
}