package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.res.dto.ProvinceBrandDto;
import com.gg.gpos.res.entity.ProvinceBrand;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface ProvinceBrandMapper {
	ProvinceBrand dtoToEntity(ProvinceBrandDto provinceBrandDto);
	ProvinceBrandDto entityToDto(ProvinceBrand provinceBrand);
}