package com.gg.gpos.menu.dto;

import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class OrderCategoryDto extends BaseDto{
	  private Long id;
	  private Long itemId;
	  private Long parentId;
	  private String code;
	  private String name;
	  private Integer status;
	  private String rightLvl;
	  private Integer objectSifr;
	  private Integer flags;
  
//For processing in form
	  private boolean selected;
	  private List<Long> featureIds;
	  private List<MultipartFile> photos;
	  private List<String> photoUrls;
	  private MultipartFile avatar;
	  private String avatarUrl;
}