package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.AreaDto;
import com.gg.gpos.menu.entity.Area;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface AreaMapper {
	Area dtoToEntity(AreaDto areaDto);
	
	@Mapping(target = "kds", expression = "java(null)")
	AreaDto entityToDto(Area area);
}