package com.gg.gpos.menu.mapper;

import com.gg.gpos.menu.dto.*;
import com.gg.gpos.menu.entity.*;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface CoCategoryMapper {
	CoCategory dtoToEntity(CoCategoryDto coCategoryDto);
	CoCategoryDto entityToDto(CoCategory coCategory);
	
	@Mapping(target = "so", expression = "java(null)")
	@Mapping(target = "soCategoryFoodGroups", expression = "java(null)")
	SoCategoryDto soCategoryToSoCategoryDto(SoCategory soCategory);
	
	@Mapping(target = "soCategories", expression = "java(null)")
	SoDto soToSoDto(So so);
	
	@Mapping(target = "coCategory", expression = "java(null)")
	CoFoodGroupDisplayDto coFoodGroupDisplayToCoFoodGroupDisplayDto(CoFoodGroupDisplay coFoodGroupDisplay);

	@Mapping(target = "coCategory", expression = "java(null)")
	DigitalMenuDto digitalMenuToDigitalMenuDto(DigitalMenu digitalMenu);
}