package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.CoDto;
import com.gg.gpos.menu.dto.CoFoodItemDto;
import com.gg.gpos.menu.dto.CofoodItemModifierDto;
import com.gg.gpos.menu.dto.FeatureDto;
import com.gg.gpos.menu.dto.FoodItemDto;
import com.gg.gpos.menu.dto.ModifierDto;
import com.gg.gpos.menu.dto.RelatedFoodItemDto;
import com.gg.gpos.menu.dto.ToppingFoodItemDto;
import com.gg.gpos.menu.entity.Co;
import com.gg.gpos.menu.entity.CoFoodItem;
import com.gg.gpos.menu.entity.CoFoodItemModifier;
import com.gg.gpos.menu.entity.Feature;
import com.gg.gpos.menu.entity.FoodItem;
import com.gg.gpos.menu.entity.Modifier;
import com.gg.gpos.menu.entity.RelatedFoodItem;
import com.gg.gpos.menu.entity.ToppingFoodItem;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface CoFoodItemMapper {
	CoFoodItem dtoToEntity(CoFoodItemDto coFoodItemDto);
	CoFoodItemDto entityToDto(CoFoodItem coFoodItem);
	
	@Mapping(target = "foodGroupItems", expression ="java(null)")
	FoodItemDto foodItemToFoodItemDto(FoodItem foodItem);
	
	@Mapping(target = "coFoodItems" , expression = "java(null)")
	FeatureDto featureToFeatureDto(Feature feature);
	
	@Mapping(target = "coFoodItems" , expression = "java(null)")
	ModifierDto modifierToModifierDto(Modifier modifier);
	
	@Mapping(target = "coFoodItems", expression = "java(null)")
	CoDto coToCoDto(Co co);
	
	@Mapping(target = "coFoodItem", expression = "java(null)")
	RelatedFoodItemDto relatedFoodItemToRelatedFoodItemDto(RelatedFoodItem relatedFoodItem);
	
	@Mapping(target = "coFoodItem", expression = "java(null)")
	ToppingFoodItemDto toppingFoodItemToToppingFoodItemDto(ToppingFoodItem toppingFoodItem); 
	
	@Mapping(target = "modifier", expression = "java(null)")
	@Mapping(target = "coFoodItem", expression = "java(null)")
	CofoodItemModifierDto cofoodItemModifierToCofoodItemModifierDto(CoFoodItemModifier coFoodItemModifier);
}