package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.CurrencyDto;
import com.gg.gpos.menu.entity.Currency;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface CurrencyMapper {
	Currency dtoToEntity(CurrencyDto currencyDto);
	CurrencyDto entityToDto(Currency currency);
}