package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.CoFoodItemDto;
import com.gg.gpos.menu.dto.FeatureDto;
import com.gg.gpos.menu.entity.CoFoodItem;
import com.gg.gpos.menu.entity.Feature;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface FeatureMapper {
	Feature dtoToEntity(FeatureDto featureDto);
	FeatureDto entityToDto(Feature feature);
	
	@Mapping(target ="foodItem" , expression = "java(null)")
	@Mapping(target ="modifiers" , expression = "java(null)")
	@Mapping(target ="relatedFoodItems" , expression = "java(null)")
	@Mapping(target ="toppingFoodItems" , expression = "java(null)")
	@Mapping(target ="features" , expression = "java(null)")
	@Mapping(target ="co" , expression = "java(null)")
	@Mapping(target ="coFoodItemModifiers" , expression = "java(null)")
	CoFoodItemDto coFoodItemToCoFoodItemDto(CoFoodItem coFoodItem);
}