package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.ModiSchemeDto;
import com.gg.gpos.menu.entity.ModiScheme;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface ModiSchemeMapper {
	ModiScheme dtoToEntity(ModiSchemeDto modiSchemeDto);
	ModiSchemeDto entityToDto(ModiScheme modiScheme);
}