package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.menu.dto.SoDto;
import com.gg.gpos.menu.entity.So;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface SoMapper {
	So dtoToEntity(SoDto soDto);
	
	@Mapping(target="soCategories", expression="java(null)")
	SoDto entityToDto(So so);
}