package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.entity.Version;
import com.gg.gpos.menu.dto.VersionDto;;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface VersionMapper {
	Version dtoToEntity(VersionDto versionDto);
	VersionDto entityToDto(Version version);
}