package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.res.dto.ProvinceBrandDto;
import com.gg.gpos.res.dto.ProvinceDto;
import com.gg.gpos.res.dto.RestaurantDto;
import com.gg.gpos.res.dto.SyncStatusDto;
import com.gg.gpos.res.entity.Province;
import com.gg.gpos.res.entity.ProvinceBrand;
import com.gg.gpos.res.entity.Restaurant;
import com.gg.gpos.res.entity.SyncStatus;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface RestaurantMapper {
	Restaurant dtoToEntity(RestaurantDto restaurantDto);
	RestaurantDto entityToDto(Restaurant restaurant);
	
	@Mapping(target = "restaurants", expression = "java(null)")
	ProvinceBrandDto provinceBrandToProvinceBrandDto(ProvinceBrand provinceBrand);
	
	@Mapping(target = "restaur", expression = "java(null)")
	SyncStatusDto syncStatusToSyncStatusDto(SyncStatus syncStatus);
	
	@Mapping(target = "zone", expression = "java(null)")
	@Mapping(target = "districts", expression = "java(null)")
	@Mapping(target = "provinceBrands", expression = "java(null)")
	ProvinceDto provinceToProvinceDto(Province province);
}