package com.gg.gpos.reference.dto;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class AttachmentDto extends BaseDto{
  private Long id;
  private Long moduleId;
  private String moduleType;
  private String functionType;
  private String name;
  private String url;
  private String absolutePath;
  private String fileName;
  private String fileType;
  private Integer version;
  private String error;
  private String syncStatus;
  private Integer restaurantCode;
  private String restaurantName;
  private String moduleCode;
}