package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.res.dto.DistrictBrandDto;
import com.gg.gpos.res.entity.DistrictBrand;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface DistrictBrandMapper {
	DistrictBrand dtoToEntity(DistrictBrandDto districtBrandDto);
	DistrictBrandDto entityToDto(DistrictBrand districtBrand);
}