package com.gg.gpos.user.dto;

import java.util.ArrayList;
import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class AppGroupDto {
  private Long id;
  private String name;
  private String description;
  private boolean enabled;
  private Integer systemGroup;
  private List<Long> roleIds = new ArrayList<Long>();
  
  private List<AppUserDto> appUsers;
  private List<RoleDto> roles;
}