package com.gg.gpos.reference.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.reference.dto.AttachmentDto;
import com.gg.gpos.reference.entity.Attachment;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface AttachmentMapper {
	Attachment dtoToEntity(AttachmentDto attachmentDto);
	AttachmentDto entityToDto(Attachment attachment);
}