package com.gg.gpos.menu.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class VersionDto {
  private Long id;
  private String tableName;
  private Integer versionNo;
}