package com.gg.gpos.user.dto;

import java.time.LocalDate;
import java.util.List;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class AppUserDto extends BaseDto {
  private Long id;
  private boolean accountExpired;
  private boolean accountLocked;
  private boolean credentialsExpired;
  private boolean accountEnabled;
  private String username;
  private String password;
  private Integer version;
  private Integer userLevel;
  private String createdBy;
  private LocalDate createdDate;
  private String modifiedBy;
  private LocalDate modifiedDate;
  private LocalDate passwordChangedDate;
  private Long profileId;
  private String profileType;
  
  private List<AppGroupDto> appGroups;
  private List<RoleDto> roles;
  private String confirmPassword;
  private Long groupId;
  private List<Long> groupIds;
  private List<Long> roleIds;
  private List<Integer> restaurantCodes;
  private StaffDto staff;
  //For processing in form
  private String selectedRestaurantCodes;
  private boolean check;
}