package com.gg.gpos.user.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.gg.gpos.user.entity.AppUser;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Repository
public interface AppUserRepository extends JpaRepository<AppUser, Long>, JpaSpecificationExecutor<AppUser> {
	AppUser findByUsernameAndAccountEnabledIsTrue(String username);
	AppUser findByUsernameAndAccountEnabledIsFalse(String username);
	@Query("select u from AppUser u where u.username=:username")
	AppUser loadUserByUsername(@Param("username") String username);
	
	@Query("select i from AppUser i where i.id=:id")
	AppUser loadUserById(@Param("id") Long id);
	
	AppUser findByUsernameAndAccountEnabledIsTrueAndPasswordChangedDateIsNull(String username);
	
}