package com.gg.gpos.menu.dto;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class AreaDto extends BaseDto {
  private Long id;
  private Integer restaurantCode;
  private String code;
  private String name;
  private String printerName;
  private String printPosCode;
  private boolean status;
  private boolean selected;
  private String type;
  
  private KdsDto kds;
  private HallplanDto hallplan;
}