package com.gg.gpos.integration.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class Restaurant {
	private Integer code;
	private String name;
	private String address;
	private String telephone;
	private String regionName;
	private String zone;
	private Integer isActive;
	private String latitude;
	private String longitude;
	private String email;
	private String gposIp;
	private String gposPort;
	
	Province province;
	District district;
	Brand brand;
}