package com.gg.gpos.user.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.user.dto.PositionDto;
import com.gg.gpos.user.entity.Position;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface PositionMapper {
	Position dtoToEntity(PositionDto positionDto);
	PositionDto entityToDto(Position position);
}