package com.gg.gpos.menu.dto;

import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class CoFoodItemDto extends BaseDto{
  private Long id;
  private Integer restaurantCode;
  private Integer maxPerTransaction;
  private Integer maxForKitchen;
  private Integer kalo;
  private Long soId;
  private String nameEn;
  private String descVn;
  private String descEn;
  private Long price;
  private boolean isCombo;
  private Integer code;
  private String nameVn;
  private Integer positionNumber;
  private Integer coImageSize;
  private String bufferLabel;
  private String infoFoodItem;
  private Integer viewType;
  private String extraFoodItem;
  private Long kaloGroupId;
  private boolean isChanged;
  private Integer hideIcon;
  private Integer numberOfPeopleEat;
  private String note;
  private String noteQuantitative;
  
  private CoDto co;
  private FoodItemDto foodItem;
  private List<ToppingFoodItemDto> toppingFoodItems;

  private List<Long> featureIds;
  public List<FeatureDto> features;
  public List<RelatedFoodItemDto> relatedFoodItems;
  public List<CofoodItemModifierDto> coFoodItemModifiers;
  private List<Long> modifierIds;
  public List<ModifierDto> modifiers;  
  private String listFeatureIds;
  private String listModifierIds;
  private List<MultipartFile> photos;
  private List<String> photoUrls;
  private MultipartFile avatar;
  private String avatarUrl;
  private String avatarName;
  private String checkAvatar;
  private String checkPhotos;
  
  private MultipartFile halfPhoto;
  private String halfPhotoUrl;
  private MultipartFile toppingPhoto;
  private String toppingPhotoUrl;
  private MultipartFile groupPhoto;
  private String groupPhotoUrl;
  private MultipartFile groupHiddenPhoto;
  private String groupHiddenPhotoUrl;
  private MultipartFile horizontalPhoto;
  private String horizontalPhotoUrl;
  private MultipartFile verticalPhoto;
  private String verticalPhotoUrl;
  private MultipartFile quarterPhoto;
  private String quarterPhotoUrl;
  private MultipartFile drinkPhoto;
  private String drinkPhotoUrl;
  
  private String relatedFCodes;
  private String relatedFNames;
  
  private MultipartFile qrOrderPhoto;
  private String qrOrderPhotoUrl;

}