package com.gg.gpos.menu.dto;



import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */

@Data
@EqualsAndHashCode(callSuper = true)
public class CofoodItemModifierDto extends BaseDto{
	  private Long id;  
	  private Long price;
	  private Integer quantity;
	  private Integer numberOfChili;
	  private Integer type;
	  private CoFoodItemDto coFoodItem;
	  private ModifierDto modifier;
	  private Long coFoodItemId;
	  private Long modifierId;
	  private String modifierCode;
	  private String modifierName;
}
