package com.gg.gpos.menu.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class FoodGroupItemDto {
  private Long id;
  private Integer restaurantCode;
  private Integer itemOrder;
  
  private FoodGroupDto foodGroup;
  private FoodItemDto foodItem;  
  
}