package com.gg.gpos.menu.dto;

import java.time.LocalDateTime;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class ParamDto extends BaseDto {
	  private Long id;
	  private Integer restaurantCode;
	  private String type;
	  private String paramCode;
	  private String paramValue;
	  private String description;
	  private boolean status;
	  private String createdBy;
	  private LocalDateTime createdDate;
	  private String modifiedBy;
	  private LocalDateTime modifiedDate;
	  private String name;
	  private GroupParamDto groupParam;
	  private Long groupParamId;
}