package com.gg.gpos.menu.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class RelatedFoodItemDto {
  private Long id;
  private Long coFoodItemId;
  private Long foodItemId;
  private String foodItemCode;
  private String foodItemName;
  private String type;
  private String nameDisplay;
  private boolean selected;
  private CoFoodItemDto coFoodItem;
  private String sapCode;
}