package com.gg.gpos.menu.dto;

import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class SoCategoryDto  extends BaseDto {
  private Long id;
  private Integer restaurantCode;
  private Long orderCategoryParentId;
  private String adultBufferTicket;
  private String kidBufferTicket;
  private Integer type;
  private boolean status;
  
  private OrderCategoryDto orderCategory;
  private SoDto so;
  
  private List<SoCategoryFoodGroupDto> soCategoryFoodGroups;
  
  
  // For processing in form
  private Long soId;
  private Long coId;
  private List<FoodGroupDto> foodGroups;
  private String updatedFoodGroups;
  private String deletedFoodGroups;
  private List<Integer> resCodes;
  private List<MultipartFile> photos;
  private List<String> photoUrls;
  private MultipartFile avatar;
  private String avatarUrl;
  private boolean override;
  
  private String selectedFoodItems;
  private String selectedFoodGroupCodes;
}