package com.gg.gpos.menu.dto;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class SoCategoryFoodGroupDto {
  private Long id;
  private Integer restaurantCode;
  private Long soCategoryId;
  private Long foodGroupId;
  private Long foodGroupParentId;
  private Integer groupOrder;
  
  private SoCategoryDto soCategory;
  private FoodGroupDto foodGroup;  
  
}