package com.gg.gpos.menu.dto;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class SoDto extends BaseDto {
	private Long id;
	private String name;
	private boolean status;
	private String createdBy;
	private LocalDateTime createdDate;
	private String modifiedBy;
	private LocalDateTime modifiedDate;
	private List<SoCategoryDto> soCategories;
	private MultipartFile fileImport;
  
	// For processing in form
	private String selectedRestaurantCodes;
	private Boolean override;
  
	public String getDisplayCreatedDate() {
		if (createdDate != null) {
			return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(createdDate);  
		} else {
			return null;
		}
	}
	
	private String displayModifiedDate;
	  public String getDisplayModifiedDate() {
		  if (modifiedDate != null) {
			  return DateTimeFormatter.ofPattern("dd-MM-yyyy").format(modifiedDate);  
		  } else {
			  return null;
		  }
	  }
}