package com.gg.gpos.user.dto;

import java.util.List;

import lombok.Data;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
public class RoleDto {
  private Long id;
  private String name;
  private String description;
  private boolean selected;
  private String type;
  
  private List<AppGroupDto> appGroups;
  private List<AppUserDto> appUsers;
}