package com.gg.gpos.menu.controller;

import java.util.List;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.gg.gpos.common.constant.SystemParamEnum;
import com.gg.gpos.controller.BaseController;
import com.gg.gpos.menu.dto.HallplanDto;
import com.gg.gpos.menu.dto.KitchenDto;
import com.gg.gpos.menu.manager.HallplanManager;
import com.gg.gpos.menu.manager.KdsManager;
import com.gg.gpos.menu.manager.KitchenManager;
import com.gg.gpos.menu.manager.KitchenTypeManager;
import com.gg.gpos.reference.dto.SystemParameterDto;
import com.gg.gpos.res.manager.SyncStatusManager;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
 @Slf4j
@Controller
public class KitchenController extends BaseController {
	@Autowired
    private KitchenManager kitchenManager;
	
	@Autowired
	private KdsManager kdsManager;
	@Autowired
    private SyncStatusManager syncStatusManager;
	@Autowired
	private HallplanManager hallplanManager;
	@Autowired
	private KitchenTypeManager kitchenTypeManager;
  
    @GetMapping("/kitchen/list")
    public ModelAndView list(@RequestParam(name="kId", required = false) Long kId, @RequestParam(name="rCode", required = true) Integer rCode) {
    	log.debug("entering 'list' method...");
		ModelAndView modelAndView = new ModelAndView("kitchen-list");
		KitchenDto criteria = new KitchenDto();
		criteria.setPage(appProperties.getDefaultPage());
		criteria.setSize(appProperties.getDefaultPageSize());
		if(kId != null) {
			criteria.setKds(kdsManager.get(kId));
		}else {
			criteria.setKds(null);
		}
		criteria.setRestaurantCode(rCode);
		Page<KitchenDto> pages = kitchenManager.gets(criteria);
		modelAndView.addObject("page", pages);
		modelAndView.addObject("criteria",criteria);
        return modelAndView;
    }
    
    @PostMapping("/kitchen/list")
    public ModelAndView search(Model model, @Valid KitchenDto criteria, BindingResult bindingResult){
    	log.debug("entering 'search' method...");
		ModelAndView modelAndView = new ModelAndView("kitchen-list");
		if(criteria.getSize() == null) {
			criteria.setPage(appProperties.getDefaultPage());
			criteria.setSize(appProperties.getDefaultPageSize());
		}
		Page<KitchenDto> pages = kitchenManager.gets(criteria);
		modelAndView.addObject("page", pages);
		modelAndView.addObject("criteria",criteria);
        return modelAndView;
    }
    
    
    @GetMapping("/kitchen/form")
    public ModelAndView show(@RequestParam(value="id", required=false) Long id, @RequestParam(value="kId", required=false) Long kId, @RequestParam(value="rCode", required=true) Integer rCode) {
    	log.debug("entering 'show' method...");
    	ModelAndView modelAndView = new ModelAndView("kitchen-form");
    	KitchenDto kitchen = new KitchenDto();
    	
    	List<HallplanDto> hallplanDtos;
    	if(id != null) {
    		kitchen = kitchenManager.get(id);
    		hallplanDtos = hallplanManager.getByKitchenIdAndResCodes(id,rCode);
    	}else {
    		hallplanDtos = hallplanManager.gets(restaurantManager.get(rCode));
    	}
		if(kId != null) {
			kitchen.setKds(kdsManager.get(kId));
		}else {
			kitchen.setKds(null);
		}
    	kitchen.setRestaurantCode(rCode);
    	
    	modelAndView.addObject("kitchen", kitchen);
    	
    	// Get list of printers from restaurant server
    	SystemParameterDto gatewayUrl = systemParameterManager.get(SystemParamEnum.API_GATEWAY_URL.param);
    	SystemParameterDto getPrintersUrl = systemParameterManager.get(SystemParamEnum.API_GET_PRINTERS_PATTERN.param);
		String apiUrl = gatewayUrl.getParamValue() + getPrintersUrl.getParamValue();

		modelAndView.addObject("printers", restaurantSyncManager.getPrinters(apiUrl, rCode));
		modelAndView.addObject("hallplans", hallplanDtos);
		modelAndView.addObject("kitchenTypes", kitchenTypeManager.gets(rCode));
		
        return modelAndView;
    }

    @PostMapping("/kitchen/save")
    public String save(@Valid KitchenDto kitchenDto, BindingResult bindingResult, HttpServletRequest request, HttpServletResponse response) {
        log.debug("entering 'save' method...");
        Locale locale = request.getLocale();
        String view;
        if (bindingResult.hasErrors()) {
        	addError(request, bindingResult.getAllErrors().toString());
        }
    	kitchenDto.setKds(null);
    	view = "redirect:/kitchen/list?rCode="+kitchenDto.getRestaurantCode();
    	try {
    		KitchenDto kitchenNew = kitchenManager.save(kitchenDto);
        	syncStatusManager.saveSttAfterEditDataBusiness(kitchenNew.getRestaurantCode());
            addMessage(request, getText("kitchen.updated", locale));
		} catch (Exception e) {
			addError(request, e.getMessage());
		}
    	
        return view;
    }
    
    @GetMapping("/kitchen/delete")
    public String delete(@RequestParam(name="id", required = true) Long id, HttpServletRequest request) {
    	log.debug("entering 'delete' method...");
    	Locale locale = request.getLocale();
    	String view;
    	KitchenDto kitchenDto = kitchenManager.get(id);
    	kitchenDto.setKds(null);
    	view = "redirect:/kitchen/list?rCode="+kitchenDto.getRestaurantCode();
    	try {
    		kitchenManager.delete(kitchenDto);
        	addMessage(request, getText("kitchen.deleted", locale));
		} catch (Exception e) {
			addError(request, e.getMessage());
		}
    	
    	return view;
    }
    
    @GetMapping("/res/get-hallplans")
    @ResponseBody
    public List<HallplanDto> getHallplans(@RequestParam(value="id", required = false)Long kitchenId,@RequestParam(value="restaurantCode", required = true) Integer resCode) {
    	log.debug("entering 'getHallplans' method...");
    	return hallplanManager.getByKitchenIdAndResCodes(kitchenId,resCode);
    }
}