package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.OrderVoidDto;
import com.gg.gpos.menu.entity.OrderVoid;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface OrderVoidMapper {
	OrderVoid dtoToEntity(OrderVoidDto orderVoidDto);
	OrderVoidDto entityToDto(OrderVoid orderVoid);
}