package com.gg.gpos.res.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.gg.gpos.res.dto.ProvinceDto;
import com.gg.gpos.res.dto.ZoneDto;
import com.gg.gpos.res.entity.Province;
import com.gg.gpos.res.entity.Zone;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface ZoneMapper {
	Zone dtoToEntity(ZoneDto zoneDto);
	ZoneDto entityToDto(Zone zone);

	@Mapping(target = "zone", expression = "java(null)")
	@Mapping(target = "districts", expression = "java(null)")
	@Mapping(target = "provinceBrands", expression = "java(null)")
	ProvinceDto provinceToProvinceDto(Province province);
	
}