package com.gg.gpos.menu.entity;

import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;

import com.gg.gpos.common.constant.FoodTypeEnum;
import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"parent", "menuType"})
@Entity
@Table(name = "food_group")
@EntityListeners(AuditEntityListener.class)
public class FoodGroup {

	  @Id
	  @GeneratedValue(strategy = GenerationType.IDENTITY)
	  @Column(name = "\"id\"", nullable = false)
	  private Long id;
	  @Column(name = "\"restaurant_code\"", nullable = true)
	  private Integer restaurantCode;
	  @Column(name = "\"type\"", nullable = true)
	  private String type;
	  @Column(name = "\"code\"", nullable = false)
	  private String code;
	  @Column(name = "\"name_en\"", nullable = true)
	  private String nameEn;
	  @Column(name = "\"name_vn\"", nullable = true)
	  private String nameVn;
	  @Column(name = "\"status\"", nullable = true)
	  private boolean status;
	  @Column(name = "\"created_by\"", nullable = true)
	  private String createdBy;
	  @Column(name = "\"created_date\"", nullable = true)
	  private LocalDateTime createdDate;
	  @Column(name = "\"modified_by\"", nullable = true)
	  private String modifiedBy;
	  @Column(name = "\"modified_date\"", nullable = true)
	  private LocalDateTime modifiedDate;
	  @Column(name = "\"level\"", nullable = true)
	  private Integer level;
	  @Column(name = "\"src_image\"", nullable = true)
	  private String srcImage;
	  @Column(name = "\"unsigned_name\"", nullable = true)
	  private String unsignedName;
  
	  @ManyToOne(fetch = FetchType.LAZY)
	  @JoinColumn(name = "\"menu_type_id\"", nullable = true)
	  private MenuType menuType;
	  
	  @ManyToOne(fetch = FetchType.LAZY)
	  @JoinColumn(name = "parent_id", nullable = true)
	  private FoodGroup parent;
	  
	  @OneToMany(mappedBy = "foodGroup",fetch = FetchType.LAZY)
	  private List<SoCategoryFoodGroup> soCategoryFoodGroups;
	  
	  @OneToMany(mappedBy = "foodGroup",fetch = FetchType.LAZY)
	  private List<FoodGroupItem> foodGroupItems;
	  
	  @Column(name = "\"changed\"", nullable = true)
	  private Integer changed;

	
	  @PrePersist
	  private void beforePersist() {
		  setType(FoodTypeEnum.MENU_GROUP.val);
		  setStatus(Boolean.TRUE.booleanValue());
		  setCreatedDate(LocalDateTime.now());
		  setModifiedDate(LocalDateTime.now());
	  }
	  
	  @PreUpdate
	  private void beforeUpdate() {
		  setType(FoodTypeEnum.MENU_GROUP.val);
		  setStatus(Boolean.TRUE.booleanValue());
		  setModifiedDate(LocalDateTime.now());
	  }
  
}