package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.OrderTypeDto;
import com.gg.gpos.menu.entity.OrderType;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface OrderTypeMapper {
	OrderType dtoToEntity(OrderTypeDto orderTypeDto);
	OrderTypeDto entityToDto(OrderType orderType);
}