package com.gg.gpos.menu.mapper;

import org.mapstruct.Mapper;

import com.gg.gpos.menu.dto.EmployeeDto;
import com.gg.gpos.menu.entity.Employee;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Mapper(componentModel = "spring")
public interface EmployeeMapper {
	Employee dtoToEntity(EmployeeDto employeeDto);
	EmployeeDto entityToDto(Employee employee);
}