package com.gg.gpos.menu.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.speedfrwk.data.jpa.audit.AuditEntityListener;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"kds", "hallplan"})
@Entity
@Table(name = "area")
@EntityListeners(AuditEntityListener.class)
public class Area {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"restaurant_code\"", nullable = true)
  private Integer restaurantCode;
  @Column(name = "\"code\"", nullable = true)
  private String code;
  @Column(name = "\"name\"", nullable = true)
  private String name;
  @Column(name = "\"printer_name\"", nullable = true)
  private String printerName;
  @Column(name = "\"print_pos_code\"", nullable = true)
  private String printPosCode;
  @Column(name = "\"status\"", nullable = true)
  private boolean status;
  @Column(name = "\"type\"", nullable = true)
  private String type;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "\"kds_id\"", nullable = true)
  private Kds kds;
  
  @ManyToOne()
  @JoinColumn(name = "\"hallplan_id\"", nullable = true)
  private Hallplan hallplan;
}