package com.gg.gpos.menu.dto;

import java.util.List;

import com.gg.gpos.common.util.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@EqualsAndHashCode(callSuper = true)
public class KitchenDto extends BaseDto {
  private Long id;
  private Integer restaurantCode;
  private String kitchenCode;
  private String kitchenType;
  private String printName;
  
  private KdsDto kds;
  private List<HallplanDto> hallplans;
  private List<Long> hallplanIds;
}