package com.gg.gpos.user.entity;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import lombok.Data;
import lombok.ToString;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Data
@ToString(exclude = {"appUsers", "appGroups"})

@Entity
@Table(name = "role")
public class Role {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"name\"", nullable = false)
  private String name;
  @Column(name = "\"description\"", nullable = true)
  private String description;
  @Column(name= "\"type\"", nullable=true)
  private String type;
  
  @ManyToMany(mappedBy = "roles")
  private List<AppGroup> appGroups;
  
  @ManyToMany(mappedBy = "roles")
  private List<AppUser> appUsers;
}