package com.gg.gpos.menu.manager;

import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Service;

import com.gg.gpos.menu.dto.CurrencyDto;
import com.gg.gpos.menu.entity.Currency;
import com.gg.gpos.menu.mapper.CurrencyMapper;
import com.gg.gpos.menu.repository.CurrencyRepository;
import com.gg.gpos.menu.specification.CurrencyRateSpecification;

import lombok.extern.slf4j.Slf4j;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Slf4j
@Service
@Transactional
public class CurrencyManager {
	@Autowired
	private CurrencyRepository currencyRepository;
	@Autowired
	private CurrencyMapper currencyMapper;
	@Autowired
	private CurrencyRateSpecification<Currency> currencyRateSpecification;
	
	public void save(List<CurrencyDto> currencyDtos) {
		log.debug("PROCESS: SAVE CURRENCY, CURRENCY_DTOS: {}", currencyDtos);
		if (!currencyDtos.isEmpty()) {
			currencyDtos.stream().forEach(f -> {
				Currency currency = Optional.ofNullable(f).map(currencyMapper::dtoToEntity).orElse(null);
				if (currency != null) {
					currencyRepository.save(currency);
				}
			});
		}
	}
	
	public Page<CurrencyDto> gets(CurrencyDto criteria){
		log.debug("PROCESS: GETS CURRENCY, CURRENCY_DTO: {}", criteria);
		Specification<Currency> spec = Specification.where(currencyRateSpecification.search(criteria.getRateClass(), criteria.getStatus()));
		Page<Currency> page = currencyRepository.findAll(spec, PageRequest.of(criteria.getPage(), criteria.getSize()));
		return new PageImpl<>(page.getContent().stream().map(currencyMapper::entityToDto).collect(Collectors.toList()),PageRequest.of(criteria.getPage(), criteria.getSize()), page.getTotalElements());
	}
	
}