package com.gg.gpos.menu.repository;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import com.gg.gpos.menu.entity.Feature;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Repository
public interface FeatureRepository extends JpaRepository<Feature, Long>, JpaSpecificationExecutor<Feature> {
	List<Feature> findByStatus(Integer status);
	@Query("from Feature f where f.code = :code and status != 0")
	List<Feature> findByCodeAndCheckStatus(@Param("code") String code);
	List<Feature> findByRestaurantCode(Integer resCode);
	@Modifying
	@Query("update Feature f set f.status = 0 where f.id= :id")
	public void changeStatus(@Param("id") Long id);
	@Query("from Feature f where f.status=3")
	List<Feature> findActives();
}