package com.gg.gpos.menu.repository;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.gg.gpos.menu.entity.Kds;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Repository
public interface KdsRepository extends JpaRepository<Kds, Long>, JpaSpecificationExecutor<Kds> {
	List<Kds> findByStatusIsTrue();
	Kds findByRestaurantCode(Integer resCode);
}