package com.gg.gpos.menu.repository;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.gg.gpos.menu.entity.CoFoodItem;
import com.gg.gpos.menu.entity.RelatedFoodItem;

/**
 * Generated by Speed Generator
 * 
 * @author <a href="mailto:ngtrungkien@gmail.com">Kien Nguyen</a>
 */
@Repository
public interface RelatedFoodItemRepository extends JpaRepository<RelatedFoodItem, Long>, JpaSpecificationExecutor<RelatedFoodItem> {
	List<RelatedFoodItem> findByCoFoodItem(CoFoodItem coFoodItem);
	List<RelatedFoodItem> findByCoFoodItemAndType(CoFoodItem coFoodItem,String type);
	List<RelatedFoodItem> findByTypeAndCoFoodItem_Id(String type,Long cId);
	void deleteByCoFoodItemIn(List<CoFoodItem> coFoodItems);
	void deleteByCoFoodItem(CoFoodItem coFoodItem);
	void deleteByCoFoodItemAndType(CoFoodItem coFoodItem,String type);
}